workers_dev = true
name = "hirejuniors-dev"
compatibility_date = "2024-11-18"
main = "./workers/app.ts"
assets = { directory = "./dist/client" }
upload_source_maps = true

[[d1_databases]]
binding = "DB"
database_name = "hirejuniors-db"
database_id = "0cf03998-30a5-4a7f-a496-42ea5051a36c"
migrations_dir = "drizzle"

# [ai]
# binding = "AI"

[triggers]
# trigger every 10 days
crons = ["* * * 10 *"]

[[workflows]]
name = "cloudflareJobs"
binding = "CLOUDFLAREJOBS"
class_name = "CloudflareWorkflow"

[[workflows]]
name = "amazon"
binding = "AMAZON"
class_name = "AmazonWorkflow"
