workers_dev = true
name = "hirejuniors-dev"
compatibility_date = "2024-11-18"
main = "./workers/app.ts"
assets = { directory = "./dist/client" }
upload_source_maps = true

[[d1_databases]]
binding = "DB"
database_name = "your-database-name"
database_id = "your-database-id"
migrations_dir = "drizzle"

# [ai]
# binding = "AI"

[triggers]
# trigger every 10 days
crons = ["* * * 10 *"]

[[workflows]]
name = "amazon"
binding = "AMAZON"
class_name = "AmazonWorkflow"
